# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'basic.ui'
#
# Created: Wed Dec 12 12:34:32 2012
#      by: PyQt4 UI code generator 4.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Basic(object):
    def setupUi(self, Basic):
        Basic.setObjectName(_fromUtf8("Basic"))
        Basic.resize(618, 750)
        self.verticalLayout = QtGui.QVBoxLayout(Basic)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.widget = QtGui.QWidget(Basic)
        self.widget.setMinimumSize(QtCore.QSize(600, 320))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.label_5 = QtGui.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(466, 50, 16, 20))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_7 = QtGui.QLabel(self.widget)
        self.label_7.setGeometry(QtCore.QRect(410, 290, 21, 20))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_11 = QtGui.QLabel(self.widget)
        self.label_11.setGeometry(QtCore.QRect(580, 220, 21, 21))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_6 = QtGui.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(580, 120, 31, 20))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_9 = QtGui.QLabel(self.widget)
        self.label_9.setGeometry(QtCore.QRect(473, 290, 21, 20))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_8 = QtGui.QLabel(self.widget)
        self.label_8.setGeometry(QtCore.QRect(442, 290, 21, 20))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_13 = QtGui.QLabel(self.widget)
        self.label_13.setGeometry(QtCore.QRect(580, 160, 21, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_10 = QtGui.QLabel(self.widget)
        self.label_10.setGeometry(QtCore.QRect(382, 50, 21, 20))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_12 = QtGui.QLabel(self.widget)
        self.label_12.setGeometry(QtCore.QRect(580, 190, 21, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_14 = QtGui.QLabel(self.widget)
        self.label_14.setGeometry(QtCore.QRect(510, 50, 31, 20))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(self.widget)
        self.label_15.setGeometry(QtCore.QRect(10, 20, 591, 281))
        self.label_15.setText(_fromUtf8(""))
        self.label_15.setPixmap(QtGui.QPixmap(_fromUtf8(":/Tamer/P-img-small.png")))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_16 = QtGui.QLabel(self.widget)
        self.label_16.setGeometry(QtCore.QRect(412, 50, 21, 20))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_17 = QtGui.QLabel(self.widget)
        self.label_17.setGeometry(QtCore.QRect(507, 290, 21, 20))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.verticalLayout.addWidget(self.widget)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_3 = QtGui.QLabel(Basic)
        self.label_3.setMinimumSize(QtCore.QSize(60, 0))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_4 = QtGui.QLabel(Basic)
        self.label_4.setMinimumSize(QtCore.QSize(60, 0))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 1, 0, 1, 1)
        self.leHWI = QtGui.QLineEdit(Basic)
        self.leHWI.setReadOnly(True)
        self.leHWI.setObjectName(_fromUtf8("leHWI"))
        self.gridLayout_3.addWidget(self.leHWI, 0, 1, 1, 1)
        self.leVER = QtGui.QLineEdit(Basic)
        self.leVER.setReadOnly(True)
        self.leVER.setObjectName(_fromUtf8("leVER"))
        self.gridLayout_3.addWidget(self.leVER, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.groupBox = QtGui.QGroupBox(Basic)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.cbOut0 = QtGui.QCheckBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbOut0.sizePolicy().hasHeightForWidth())
        self.cbOut0.setSizePolicy(sizePolicy)
        self.cbOut0.setObjectName(_fromUtf8("cbOut0"))
        self.gridLayout.addWidget(self.cbOut0, 0, 0, 1, 1)
        self.cbOut1 = QtGui.QCheckBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbOut1.sizePolicy().hasHeightForWidth())
        self.cbOut1.setSizePolicy(sizePolicy)
        self.cbOut1.setObjectName(_fromUtf8("cbOut1"))
        self.gridLayout.addWidget(self.cbOut1, 1, 0, 1, 1)
        self.cbOut2 = QtGui.QCheckBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbOut2.sizePolicy().hasHeightForWidth())
        self.cbOut2.setSizePolicy(sizePolicy)
        self.cbOut2.setObjectName(_fromUtf8("cbOut2"))
        self.gridLayout.addWidget(self.cbOut2, 0, 1, 1, 1)
        self.cbOut3 = QtGui.QCheckBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbOut3.sizePolicy().hasHeightForWidth())
        self.cbOut3.setSizePolicy(sizePolicy)
        self.cbOut3.setObjectName(_fromUtf8("cbOut3"))
        self.gridLayout.addWidget(self.cbOut3, 1, 1, 1, 1)
        self.cbOut4 = QtGui.QCheckBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbOut4.sizePolicy().hasHeightForWidth())
        self.cbOut4.setSizePolicy(sizePolicy)
        self.cbOut4.setObjectName(_fromUtf8("cbOut4"))
        self.gridLayout.addWidget(self.cbOut4, 0, 2, 1, 1)
        self.cbOut5 = QtGui.QCheckBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbOut5.sizePolicy().hasHeightForWidth())
        self.cbOut5.setSizePolicy(sizePolicy)
        self.cbOut5.setObjectName(_fromUtf8("cbOut5"))
        self.gridLayout.addWidget(self.cbOut5, 1, 2, 1, 1)
        self.cbOut6 = QtGui.QCheckBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbOut6.sizePolicy().hasHeightForWidth())
        self.cbOut6.setSizePolicy(sizePolicy)
        self.cbOut6.setObjectName(_fromUtf8("cbOut6"))
        self.gridLayout.addWidget(self.cbOut6, 0, 3, 1, 1)
        self.cbOut7 = QtGui.QCheckBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbOut7.sizePolicy().hasHeightForWidth())
        self.cbOut7.setSizePolicy(sizePolicy)
        self.cbOut7.setObjectName(_fromUtf8("cbOut7"))
        self.gridLayout.addWidget(self.cbOut7, 1, 3, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.verticalLayout.addWidget(self.groupBox)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label = QtGui.QLabel(Basic)
        self.label.setMinimumSize(QtCore.QSize(60, 0))
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.label_2 = QtGui.QLabel(Basic)
        self.label_2.setMinimumSize(QtCore.QSize(60, 0))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 2, 0, 1, 1)
        self.leFosc = QtGui.QLineEdit(Basic)
        self.leFosc.setObjectName(_fromUtf8("leFosc"))
        self.gridLayout_2.addWidget(self.leFosc, 1, 1, 1, 1)
        self.leFout = QtGui.QLineEdit(Basic)
        self.leFout.setObjectName(_fromUtf8("leFout"))
        self.gridLayout_2.addWidget(self.leFout, 2, 1, 1, 1)
        self.cbOscDisable = QtGui.QCheckBox(Basic)
        self.cbOscDisable.setMinimumSize(QtCore.QSize(220, 0))
        self.cbOscDisable.setObjectName(_fromUtf8("cbOscDisable"))
        self.gridLayout_2.addWidget(self.cbOscDisable, 1, 2, 1, 1)
        self.cbAutoStart = QtGui.QCheckBox(Basic)
        self.cbAutoStart.setMinimumSize(QtCore.QSize(220, 0))
        self.cbAutoStart.setObjectName(_fromUtf8("cbAutoStart"))
        self.gridLayout_2.addWidget(self.cbAutoStart, 2, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.line = QtGui.QFrame(Basic)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        self.gGps = QtGui.QGroupBox(Basic)
        self.gGps.setObjectName(_fromUtf8("gGps"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.gGps)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_18 = QtGui.QLabel(self.gGps)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_4.addWidget(self.label_18, 1, 0, 1, 1)
        self.label_19 = QtGui.QLabel(self.gGps)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_4.addWidget(self.label_19, 2, 0, 1, 1)
        self.le1PPS = QtGui.QLineEdit(self.gGps)
        self.le1PPS.setReadOnly(True)
        self.le1PPS.setObjectName(_fromUtf8("le1PPS"))
        self.gridLayout_4.addWidget(self.le1PPS, 1, 1, 1, 1)
        self.leCalcFout = QtGui.QLineEdit(self.gGps)
        self.leCalcFout.setReadOnly(True)
        self.leCalcFout.setObjectName(_fromUtf8("leCalcFout"))
        self.gridLayout_4.addWidget(self.leCalcFout, 2, 1, 1, 1)
        self.cbGPSSync = QtGui.QCheckBox(self.gGps)
        self.cbGPSSync.setObjectName(_fromUtf8("cbGPSSync"))
        self.gridLayout_4.addWidget(self.cbGPSSync, 0, 0, 1, 1)
        self.lbGpsInfo = QtGui.QLabel(self.gGps)
        self.lbGpsInfo.setText(_fromUtf8(""))
        self.lbGpsInfo.setAlignment(QtCore.Qt.AlignCenter)
        self.lbGpsInfo.setObjectName(_fromUtf8("lbGpsInfo"))
        self.gridLayout_4.addWidget(self.lbGpsInfo, 0, 1, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_4)
        self.verticalLayout.addWidget(self.gGps)
        spacerItem = QtGui.QSpacerItem(20, 75, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.btStore = QtGui.QPushButton(Basic)
        self.btStore.setObjectName(_fromUtf8("btStore"))
        self.horizontalLayout_2.addWidget(self.btStore)
        self.btLoad = QtGui.QPushButton(Basic)
        self.btLoad.setObjectName(_fromUtf8("btLoad"))
        self.horizontalLayout_2.addWidget(self.btLoad)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.btSet = QtGui.QPushButton(Basic)
        self.btSet.setObjectName(_fromUtf8("btSet"))
        self.horizontalLayout_2.addWidget(self.btSet)
        self.btGet = QtGui.QPushButton(Basic)
        self.btGet.setObjectName(_fromUtf8("btGet"))
        self.horizontalLayout_2.addWidget(self.btGet)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Basic)
        QtCore.QMetaObject.connectSlotsByName(Basic)

    def retranslateUi(self, Basic):
        Basic.setWindowTitle(QtGui.QApplication.translate("Basic", "ClockTamer Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Basic", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Basic", "4+", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Basic", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Basic", "0+", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Basic", "5+", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Basic", "4-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Basic", "7-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Basic", "3-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Basic", "7+", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Basic", "0-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Basic", "3+", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Basic", "5-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Basic", "HWI:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Basic", "VER:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Basic", "Outputs Enabled", None, QtGui.QApplication.UnicodeUTF8))
        self.cbOut0.setText(QtGui.QApplication.translate("Basic", "OUT 0", None, QtGui.QApplication.UnicodeUTF8))
        self.cbOut1.setText(QtGui.QApplication.translate("Basic", "OUT 1", None, QtGui.QApplication.UnicodeUTF8))
        self.cbOut2.setText(QtGui.QApplication.translate("Basic", "OUT 2", None, QtGui.QApplication.UnicodeUTF8))
        self.cbOut3.setText(QtGui.QApplication.translate("Basic", "OUT 3", None, QtGui.QApplication.UnicodeUTF8))
        self.cbOut4.setText(QtGui.QApplication.translate("Basic", "OUT 4", None, QtGui.QApplication.UnicodeUTF8))
        self.cbOut5.setText(QtGui.QApplication.translate("Basic", "OUT 5", None, QtGui.QApplication.UnicodeUTF8))
        self.cbOut6.setText(QtGui.QApplication.translate("Basic", "OUT 6", None, QtGui.QApplication.UnicodeUTF8))
        self.cbOut7.setText(QtGui.QApplication.translate("Basic", "OUT 7", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Basic", "Fosc", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Basic", "Fout", None, QtGui.QApplication.UnicodeUTF8))
        self.leFosc.setInputMask(QtGui.QApplication.translate("Basic", "09\'999\'999 \\Hz;_", None, QtGui.QApplication.UnicodeUTF8))
        self.leFosc.setText(QtGui.QApplication.translate("Basic", "20\'000\'000 Hz", None, QtGui.QApplication.UnicodeUTF8))
        self.leFout.setInputMask(QtGui.QApplication.translate("Basic", "09\'999\'999 \\Hz;_", None, QtGui.QApplication.UnicodeUTF8))
        self.leFout.setText(QtGui.QApplication.translate("Basic", "52\'000\'000 Hz", None, QtGui.QApplication.UnicodeUTF8))
        self.cbOscDisable.setText(QtGui.QApplication.translate("Basic", "Disable internal oscillator", None, QtGui.QApplication.UnicodeUTF8))
        self.cbAutoStart.setText(QtGui.QApplication.translate("Basic", "Start on power up", None, QtGui.QApplication.UnicodeUTF8))
        self.gGps.setTitle(QtGui.QApplication.translate("Basic", "GPS", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Basic", "1PPS Count", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("Basic", "Calculated Fout", None, QtGui.QApplication.UnicodeUTF8))
        self.cbGPSSync.setText(QtGui.QApplication.translate("Basic", "Keep in sync with GPS", None, QtGui.QApplication.UnicodeUTF8))
        self.btStore.setText(QtGui.QApplication.translate("Basic", "Store to EEPROM", None, QtGui.QApplication.UnicodeUTF8))
        self.btLoad.setText(QtGui.QApplication.translate("Basic", "Load from EEPROM", None, QtGui.QApplication.UnicodeUTF8))
        self.btSet.setText(QtGui.QApplication.translate("Basic", "SET", None, QtGui.QApplication.UnicodeUTF8))
        self.btGet.setText(QtGui.QApplication.translate("Basic", "GET", None, QtGui.QApplication.UnicodeUTF8))

import res_rc
import res_rc
